// The following html tags will be input into the needToKnow window that is seen when it open
var $needToKnowContent = [
	'<h3>OVERVIEW OF MA3000</h3>',
	'<p>This course follows Learning Languages in the New Zealand Curriculum up to Level 8 and has an emphasis on communicating in M&amacr;ori. The course prepares you to gain 28 NCEA Level 3 credits. You can gain 16 credits from the internally assessed activities in this course. The rest of the credits come from externally assessed activities.</p>',
	'<h3>HOW TO GET THE MOST OUT OF THIS COURSE</h3>',
	'<p><b>GENERAL LANGUAGE TIPS</b></p>',
	'<ul>',
		'<li>',
			'<p style="margin-bottom:0"><b>A little bit and often</b></p>',
			'<p>The rule of thumb for language learning is to do &lsquo;a little, often, with lots of revision&rsquo;. Have a study plan and keep to it. The notes here and advice from your teacher throughout the modules will help you achieve this. Try to complete one lesson at a time and build in time to revise vocabulary regularly.</p>',
		'</li>',
		'<li>',
			'<p style="margin-bottom:0"><b>Checking your own work</b></p>',
			'<p>You will be able to check most of your own work as you go through the lessons. This gives you immediate feedback so that you can learn from your mistakes. It is important that you do this carefully. Compare your answers with the model answers. If your answers are different, go back to the explanations so you know where you went wrong and how to improve. If you are still unsure after doing this, ask your teacher for help.</p>',
		'</li>',
		'<li>',
			'<p style="margin-bottom:0"><b>Learn your words regularly</b></p>',
			'<p>When speaking or writing in another language, use the words and phrases that you know well. To increase the amount of language you can use it&rsquo;s important to learn the words as you go and revise frequently - daily, weekly, monthly.</p>',
		'</li>',
		'<li>',
			'<p style="margin-bottom:0"><b>Free subscription to online vocabulary learning site</b></p>',
			'<p>Language Perfect is an online programme that all students at Te Kura can access. It is part of a bigger website called Education Perfect. Within a few weeks of starting your course you will be able to log in to the website and start practising words and phrases relevant to your course. You will be able to see your score increase every time you go in and practise. Sometimes there are competitions to enter and there is also an APP.',
			'<br><b>Steps to log in:</b>',
			'<br>Go to <a href="https://www.educationperfect.com/app/" target="_blank">Education Perfect</a> and enter your username and password</p>',
			'<br>',
			'<p><b>Log in using:</b>',
			'<br>Username: TK (plus your Te Kura Student ID with no spaces).',
			'<br>Passwords: FirstName (for new users -use a capital letter at the beginning of your name).</p>',
			'<p>Passwords will be unchanged for existing users. You will be prompted to change your password at the first log in. If you have difficulties then email the Education Perfect Support Team support@educationperfect.com. You will need to provide your <b>Te Kura email address</b> and your Te Kura student ID #. Education Perfect will set you up and email you back.</p>',
		'</li>',
	'</ul>',
	'<h3>Audio files</h3>',
	'<p>You will need a quiet room where you can listen to the audio files and practise speaking out loud.</p>',
	'<p>When listening to the audio files, listen as many times as you want. If you do not understand something the first time, go over it until you do. The M&amacr;ori you hear will provide a good model, so the more you listen and use it for practising aloud, the more your brain will absorb and remember - the sounds, the rhythm and the tune of real M&amacr;ori.</p><p>',
	'From time to time, record yourself speaking M&amacr;ori, even if it is not for an assessment. If you think you can do an activity better, try again and again until it sounds right to you. When you record for an assessment:</p>',
	'<ul>',
		'<li>find a quiet place</li>',
		'<li>turn off all background noise (music, radio, television)</li>',
		'<li>check your recording equipment. Make sure it&rsquo;s in good working order. If it runs on batteries, check that they have enough power</li>',
		'<li>check your recording before you submit it.</li>',
	'</ul>',
	'<h3>FAQs</h3>',
	'<p><b>What extra equipment do I need to complete this course?</b></p>',
	'<ul>',
		'<li>HEADPHONES: to listen to the audio files</li>',
		'<li>A RECORDING DEVICE: to audio or video record your own speaking of M&amacr;ori.</li>',
		'<ol style="margin-top:0">',
			'<p style="margin: 10px 0 0 0"><b>There are three steps involved when recording:</b></p>',
			'<li>Record your voice: You can use your phone or online software. You can use any software to do your recordings but we prefer to receive WAV or MP3 files for audio, and MP4 files for video.</li>',
			'<li>Label your file: Once you have recorded your WAV/MP3/MP4 file, label it with the module name, activity number, task and your name like this <b>MAO3001_8A_Speaking_John_Smith</b></li>',
			'<li>Upload your file to the relevant OTLE dropbox.</li>',
		'</ol>',

			'<p style="margin: 10px 0 0 0"><b>Ensure you also:</b></p>',
			'<li>Check your recording equipment. Make sure it&rsquo;s in good working order. If it runs on batteries, check that they have enough power.</li>',
			'<li>Check your recording before you submit it.</li>',
		'</ul>',
	'</ul>',
	'<h3>ASSESSMENT</h3>',
	'<p>In this Te Kura course you will be working towards increasing your ability to understand and use M&amacr;ori. You will have opportunities to gain credits in five Achievement Standards - three will be internally assessed and two will be assessed through the NZQA examinations at the end of the year. Below is a brief overview of the assessments. You will be given more detailed instructions and the criteria in your module work. You can also find information on the NZQA website by searching for the relevant Achievement Standard (AS) number.</p>',
	'<p>Here is a list of the standards offered in MA3000.</p>',

	'<table>',
		'<tr>',
			'<td><b>Standard number</b></td>',
			'<td><b>Standard title</b></td>',
			'<td><b>Study material (code)</b></td>',
			'<td><b>Further assessment opportunity</b></td>',
		'</tr>',
		'<tr>',
			'<td>',
				'<p>AS91650</p>',
				<!-- '<p>M&amacr;ori 3.1</p>', -->
				'<p>Interal</p>',
				'<p>4 credits</p>',
			'</td>',
			'<td>',
				'<p>Whakarongo kia m&omacr;hio ki te reo M&amacr;ori o te ao wh&amacr;nui</p>',
			'</td>',
			'<td>',
				'<p>MAO3001</p>',
				'<p>MAO3002</p>',
				'<p>MAO3003</p>',
			'</td>',
			'<td></td>',
		'</tr>',
		'<tr>',
			'<td>',
				'<p>AS91651</p>',
				<!-- '<p>M&amacr;ori 3.2</p>', -->
				'<p>Interal</p>',
				'<p>6 credits</p>',
			'</td>',
			'<td>',
				'<p>K&omacr;rero kia whakamahi i te reo M&amacr;ori o te ao wh&amacr;nui</p>',
			'</td>',
			'<td>',
				'<p>MAO3001</p>',
				'<p>MAO3002</p>',
				'<p>MAO3003</p>',
			'</td>',
			'<td></td>',
		'</tr>',
		'<tr>',
			'<td>',
				'<p>AS91652</p>',
				<!-- '<p>M&amacr;ori 3.3</p>', -->
				'<p>External</p>',
				'<p>6 credits</p>',
			'</td>',
			'<td>',
				'<p>Waihanga tuhinga whai take i te reo M&amacr;ori o te ao wh&amacr;nui</p>',
			'</td>',
			'<td>',
				'<p>MAO3004</p>',
			'</td>',
			'<td></td>',
		'</tr>',
		'<tr>',
			'<td>',
				'<p>AS91653</p>',
				<!-- '<p>M&amacr;ori 3.4</p>', -->
				'<p>External</p>',
				'<p>6 credits</p>',
			'</td>',
			'<td>',
				'<p>P&amacr;nui kia m&omacr;hio ki te reo M&amacr;ori o te ao wh&amacr;nui</p>',
			'</td>',
			'<td>',
				'<p>MAO3004</p>',
			'</td>',
			'<td></td>',
		'</tr>',
		'<tr>',
			'<td>',
				'<p>AS91654</p>',
				<!-- '<p>M&amacr;ori 3.5</p>', -->
				'<p>Internal</p>',
				'<p>6 credits</p>',
			'</td>',
			'<td>',
				'<p>Tuhi i te reo M&amacr;ori o te ao wh&amacr;nui</p>',
			'</td>',
			'<td>',
				'<p>MAO3001</p>',
				'<p>MAO3002</p>',
				'<p>MAO3003</p>',
			'</td>',
			'<td></td>',
		'</tr>',
	'</table>',
	'<br>',
	'<p>Discuss with your teacher which assessment tasks you wish to work towards.</p>',
	'<h3>SUGGESTED PROGRAMME</h3>',
	'<p><a href="https://tekura.desire2learn.com/shared/'+$nceaLevel+'/'+$courseCode+'/baseFiles/PDFs/'+$courseCode+' POL.pdf" target="_blank">Click here see an example</a> of a suggested one-year plan. It gives an idea of how you might work towards completing the '+$courseCode+' course. Note that it assumes you are enrolled for the full school year.</p>',
	'<p>However, you may also enrol with Te Kura partway through the year and continue your studies the following year. You may choose to select only some of the topics and standards or complete them in a different order, depending on your circumstances. Feel free to discuss your individual programme with your subject teacher, who will be willing to adjust the programme to suit your needs.</p>',
	'<h3>TIME COMMITMENT</h3>',
	'<p>This will depend on the number of standards you choose to complete. A full time M&amacr;ori course at this level will take approximately 5 hours a week for the full year.</p>',
	'<h3>Additional course materials</h3>',
	'<table>',
		'<tr>',
			'<td><b>Resources</b></td>',
			'<td><b>Description</b></td>',
			'<td><b>Website</b></td>',
		'</tr>',
		'<tr>',
			'<td>',
				'<p>Te Aka online dictionary</p>',
			'</td>',
			'<td>',
				'<p>English/M&amacr;ori online dictionary</p>',
			'</td>',
			'<td>',
				'<p><a href="http://www.maoridictionary.co.nz" target="_blank">www.maoridictionary.co.nz</a></p>',
			'</td>',
		'</tr>',
		'<tr>',
			'<td>',
				'<p>Te Ara - The Encyclopedia of New Zealand</p>',
			'</td>',
			'<td>',
				'<p>Te Ara - The Encyclopedia of New Zealand is building a comprehensive guide to our peoples, natural environment, history, culture,economy and society.</p>',
			'</td>',
			'<td>',
				'<p><a href="http://www.teara.govt.nz" target="_blank">www.teara.govt.nz</a></p>',
			'</td>',
		'</tr>',
		'<tr>',
			'<td>',
				'<p>Te Papa Tongarewa Museum of New Zealand</p>',
			'</td>',
			'<td>',
				'<p>Te Papa is New Zealand&rsquo;s national museum, renowned for being bicultural, scholarly, innovative, and fun.</p>',
			'</td>',
			'<td>',
				'<p><a href="http://www.tepapa.govt.nz." target="_blank">www.tepapa.govt.nz.</a></p>',
			'</td>',
		'</tr>',
		'<tr>',
			'<td>',
				'<p>Te Kete Ipurangi (TKI)</p>',
			'</td>',
			'<td>',
				'<p>TKI is a bilingual portal-plus web community which provides educational material for teachers, school managers, and the wider education community.</p>',
			'</td>',
			'<td>',
				'<p><a href="http://www.tki.org.nz" target="_blank">www.tki.org.nz</a></p>',
			'</td>',
		'</tr>',
		'<tr>',
			'<td>',
				'<p>Te Whanake M&amacr;ori language online</p>',
			'</td>',
			'<td>',
				'<p>Te Whanake M&amacr;ori language learning online series - resources, M&amacr;ori dictionary, podcasts, animated movies, forums and other online resources and activities.</p>',
			'</td>',
			'<td>',
				'<p><a href="http://www.tewhanake.maori.nz" target="_blank">www.tewhanake.maori.nz</a></p>',
			'</td>',
		'</tr>',
	'</table>',
	'<br>',
	'<h3>UNDERSTANDING TE KURA CODES</h3>',
	'<p>Your course code is: <b>MA3000</b>. MA is the code for M&amacr;ori and 3 refers to NCEA Level 3.</p>',
	'<p><b>MAO3---</b> refers to a module that covers a particular learning topic in the MA3000 course.',
	'<br><b>MAO3---Y1</b> at the end of a module code indicates a writing folio assessment task.',
	'<br><b>MAO3---Y3</b> Y3 at the end of a module code indicates a speaking assessment task.</p>',
	'<p><b>AS</b> is the code for Achievement Standard.</p>',
]